version: '2.3'

services:

  aq_container:
    image: aq_image
    container_name: aq_container
    working_dir: /code
    build:
      context: ../
      dockerfile: docker/Dockerfile

# Setup environment variables:
    environment:
      - PYTHONPATH=/code
      
# Setup the ports you want to expose:
    ports:
      # Jupyter port
      - "8888:8888"
      - "5000:5000"

# Setup the volumes you want to share:
    volumes:
      - ../:/code

# By default this container stay alive without running any command 
    command: tail /dev/null -f
# If installed, you can start Jupyter Notebook every time you run the container
    #command: jupyter notebook --allow-root --ip=0.0.0.0